name: 'Auto Release Action Semantic'
description: 'Automatically creates semantic versioned releases based on conventional commit messages'
author: 'Benyaminrmb'

branding:
  icon: 'tag'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup GitHub CLI
      shell: bash
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Run Release Script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/release.sh
        ${{ github.action_path }}/scripts/release.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

inputs:
  github_token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}