name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Release
        uses: Benyaminrmb/auto-release-action@v1
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}