name: Update Documentation

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/update-docs.sh
          $GITHUB_WORKSPACE/scripts/update-docs.sh